export enum ConnectionEnum {
  AbbeyWoodStation = "Abbey Wood Station",
  Airport = "Airport",
  Bakerloo = "Bakerloo",
  Central = "Central",
  Circle = "Circle",
  DLR = "DLR",
  District = "District",
  Exit = "Exit",
  FarringdonStation = "Farringdon Station",
  HammersmithAndCity = "Hammersmith & City",
  Jubilee = "Jubilee",
  LiverpoolStreetStation = "Liverpool Street Station",
  LondonOverground = "London Overground",
  Metropolitan = "Metropolitan",
  NationalRail = "National Rail",
  Northern = "Northern",
  PaddingtonStation = "Paddington Station",
  Piccadilly = "Piccadilly",
}
