import { StopEnum } from "./stopEnum";

export const AbbeyWoodToHeathrowTerminal4 = [
  StopEnum.AbbeyWood,
  StopEnum.Woolwich,
  StopEnum.CustomHouse,
  StopEnum.CanaryWharf,
  StopEnum.Whitechapel,
  StopEnum.LiverpoolStreet,
  StopEnum.Farringdon,
  StopEnum.TottenhamCourtRoad,
  StopEnum.BondStreet,
  StopEnum.Paddington,
  StopEnum.ActonMainLine,
  StopEnum.EalingBroadway,
  StopEnum.WestEaling,
  StopEnum.Hanwell,
  StopEnum.Southall,
  StopEnum.HayesHarlington,
  StopEnum.HeathrowTerminals23,
  StopEnum.HeathrowTerminal4,
];

export const AbbeyWoodToHeathrowTerminal5 = [
  StopEnum.AbbeyWood,
  StopEnum.Woolwich,
  StopEnum.CustomHouse,
  StopEnum.CanaryWharf,
  StopEnum.Whitechapel,
  StopEnum.LiverpoolStreet,
  StopEnum.Farringdon,
  StopEnum.TottenhamCourtRoad,
  StopEnum.BondStreet,
  StopEnum.Paddington,
  StopEnum.ActonMainLine,
  StopEnum.EalingBroadway,
  StopEnum.WestEaling,
  StopEnum.Hanwell,
  StopEnum.Southall,
  StopEnum.HayesHarlington,
  StopEnum.HeathrowTerminals23,
  StopEnum.HeathrowTerminal5,
];

export const AbbeyWoodToReading = [
  StopEnum.AbbeyWood,
  StopEnum.Woolwich,
  StopEnum.CustomHouse,
  StopEnum.CanaryWharf,
  StopEnum.Whitechapel,
  StopEnum.LiverpoolStreet,
  StopEnum.Farringdon,
  StopEnum.TottenhamCourtRoad,
  StopEnum.BondStreet,
  StopEnum.Paddington,
  StopEnum.ActonMainLine,
  StopEnum.EalingBroadway,
  StopEnum.WestEaling,
  StopEnum.Hanwell,
  StopEnum.Southall,
  StopEnum.HayesHarlington,
  StopEnum.WestDrayton,
  StopEnum.Iver,
  StopEnum.LangleyBerks,
  StopEnum.Slough,
  StopEnum.BurnhamBerks,
  StopEnum.Taplow,
  StopEnum.Maidenhead,
  StopEnum.Twyford,
  StopEnum.Reading,
];

export const LondonPaddingtonToHeathrowTerminal4 = [
  StopEnum.Paddington,
  StopEnum.ActonMainLine,
  StopEnum.EalingBroadway,
  StopEnum.WestEaling,
  StopEnum.Hanwell,
  StopEnum.Southall,
  StopEnum.HayesHarlington,
  StopEnum.HeathrowTerminals23,
  StopEnum.HeathrowTerminal4,
];

export const LondonPaddingtonToHeathrowTerminal5 = [
  StopEnum.Paddington,
  StopEnum.ActonMainLine,
  StopEnum.EalingBroadway,
  StopEnum.WestEaling,
  StopEnum.Hanwell,
  StopEnum.Southall,
  StopEnum.HayesHarlington,
  StopEnum.HeathrowTerminals23,
  StopEnum.HeathrowTerminal5,
];

export const LondonPaddingtonToReading = [
  StopEnum.Paddington,
  StopEnum.ActonMainLine,
  StopEnum.EalingBroadway,
  StopEnum.WestEaling,
  StopEnum.Hanwell,
  StopEnum.Southall,
  StopEnum.HayesHarlington,
  StopEnum.WestDrayton,
  StopEnum.Iver,
  StopEnum.LangleyBerks,
  StopEnum.Slough,
  StopEnum.BurnhamBerks,
  StopEnum.Taplow,
  StopEnum.Maidenhead,
  StopEnum.Twyford,
  StopEnum.Reading,
];

export const ShenfieldToHeathrowTerminal4 = [
  StopEnum.Shenfield,
  StopEnum.Brentwood,
  StopEnum.HaroldWood,
  StopEnum.GideaPark,
  StopEnum.Romford,
  StopEnum.ChadwellHeath,
  StopEnum.Goodmayes,
  StopEnum.SevenKings,
  StopEnum.Ilford,
  StopEnum.ManorPark,
  StopEnum.ForestGate,
  StopEnum.Maryland,
  StopEnum.StratfordLondon,
  StopEnum.Whitechapel,
  StopEnum.LiverpoolStreet,
  StopEnum.Farringdon,
  StopEnum.TottenhamCourtRoad,
  StopEnum.BondStreet,
  StopEnum.Paddington,
  StopEnum.ActonMainLine,
  StopEnum.EalingBroadway,
  StopEnum.WestEaling,
  StopEnum.Hanwell,
  StopEnum.Southall,
  StopEnum.HayesHarlington,
  StopEnum.HeathrowTerminals23,
  StopEnum.HeathrowTerminal4,
];

export const ShenfieldToHeathrowTerminal5 = [
  StopEnum.Shenfield,
  StopEnum.Brentwood,
  StopEnum.HaroldWood,
  StopEnum.GideaPark,
  StopEnum.Romford,
  StopEnum.ChadwellHeath,
  StopEnum.Goodmayes,
  StopEnum.SevenKings,
  StopEnum.Ilford,
  StopEnum.ManorPark,
  StopEnum.ForestGate,
  StopEnum.Maryland,
  StopEnum.StratfordLondon,
  StopEnum.Whitechapel,
  StopEnum.LiverpoolStreet,
  StopEnum.Farringdon,
  StopEnum.TottenhamCourtRoad,
  StopEnum.BondStreet,
  StopEnum.Paddington,
  StopEnum.ActonMainLine,
  StopEnum.EalingBroadway,
  StopEnum.WestEaling,
  StopEnum.Hanwell,
  StopEnum.Southall,
  StopEnum.HayesHarlington,
  StopEnum.HeathrowTerminals23,
  StopEnum.HeathrowTerminal5,
];

export const ShenfieldToLondonLiverpoolStreet = [
  StopEnum.Shenfield,
  StopEnum.Brentwood,
  StopEnum.HaroldWood,
  StopEnum.GideaPark,
  StopEnum.Romford,
  StopEnum.ChadwellHeath,
  StopEnum.Goodmayes,
  StopEnum.SevenKings,
  StopEnum.Ilford,
  StopEnum.ManorPark,
  StopEnum.ForestGate,
  StopEnum.Maryland,
  StopEnum.StratfordLondon,
  StopEnum.LiverpoolStreet,
];
