on:
  workflow_call:
    inputs:
      commentUpdate:
        type: boolean
        default: false
      command:
        type: string
        required: false
        default: "eas update --auto --non-interactive"
    secrets:
      EXPO_TOKEN:
        required: true

jobs:
  publish:
    name: "Publish"

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🚀 Publish app
        if: "${{ !inputs.commentUpdate }}"
        run: "${{ inputs.command }}"

      - name: 🚀 Publish app
        if: "${{ inputs.commentUpdate }}"
        uses: expo/expo-github-action/preview@v8
        with:
          command: "${{ inputs.command }}"
